# frozen_string_literal: true

module RailsInteractive
  class CLI
    class Utils
      def self.sign_project
        file = "README.md"
        msg = "\n> This project was generated by [Rails Interactive CLI](https://github.com/oguzsh/rails-interactive)"
        File.write(file, msg, mode: "a+")
      end
    end
  end
end
